---
title: "Project Proposal Work"
output: html_document
---


### Names of the students in the group.

316:4 Nico Salm, Dheeraj Pasikanti, Jinming Liu

### Communication Plan

> A brief description of how the group will communicate and work together.

We will collaborate in person and decide meet times by coordinating over text.

### Questions of Interest

> The question or questions of interest that motivate the planned study.

To understand and analyze trends between US CPI and the CPI of other countries (broken into developed and developing nations) to recognize overarching patterns, their causes, and their potential implications. 

### Source of the data

> The source(s) of data.

- A description of the data.
- Include in this description answers to these questions:
    - Who collected the data?
    - How were the data collected?
    - What are key variables in the data set, what do they measure, and how are they related to your key questions?
    - What does a single row of the data set represent in real terms?
    - If the data may be thought of as a sample from some larger population, what is that larger population?

Note: if you get the data from a data repository such as Kaggle, you will need to dig into supplementary information to answer these questions.
It is insufficient to simply report a link to a Kaggle repository.

### Graph

> Include a description of a graph which will show how the data informs the primary question of interest.

- Describe what variables you will include and what type of graph you will create.

### Model

> Include a description of a possible model for the data and associated methods of inference or prediction.

- We understand that you may not have a good grasp of these methods yet.
- We understand the choice of methods may change between the proposal and the final project.
 